name: domino_nodes
description: Functional node builders, attribute, style, event setters for domino.
version: 0.0.1
#homepage: https://www.example.com
#author: SERAGUD <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  domino: ^0.3.2
    # path: ../domino

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
